from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from pathlib import Path
from datetime import datetime


def generate_pdf_report(job_data, result):

    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    filename = f"jobguard_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = reports_dir / filename

    doc = SimpleDocTemplate(
        str(filepath),
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()
    elements = []

    # Title
    title = Paragraph(
        "<font size=20><b>JobGuard AI Fraud Detection Report</b></font>",
        styles["Title"]
    )

    elements.append(title)
    elements.append(Spacer(1, 20))

    # Job Details
    heading1 = Paragraph("<b>Job Information</b>", styles["Heading2"])
    elements.append(heading1)
    elements.append(Spacer(1, 10))

    job_table_data = [
        ["Job Title", job_data.get("title", "N/A")],
        ["Company", job_data.get("company", "N/A")],
        ["Location", job_data.get("location", "N/A")],
        ["Salary", job_data.get("salary_range", "N/A")],
    ]

    job_table = Table(job_table_data, colWidths=[150, 320])

    job_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0a1629")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
    ]))

    elements.append(job_table)
    elements.append(Spacer(1, 25))

    # Prediction Section
    heading2 = Paragraph("<b>AI Prediction Results</b>", styles["Heading2"])
    elements.append(heading2)
    elements.append(Spacer(1, 10))

    prediction_color = "#e63946" if result["prediction"] == "FAKE" else "#06a77d"

    result_table_data = [
        ["Prediction", result.get("prediction", "N/A")],
        ["Confidence", f"{round(result.get('confidence', 0) * 100, 2)}%"],
        ["Fraud Probability", f"{round(result.get('probability_fake', 0) * 100, 2)}%"],
        ["Trust Score", f"{result.get('trust_score', 0)}/100"],
        ["Risk Level", result.get("risk_level", "N/A")],
    ]

    result_table = Table(result_table_data, colWidths=[180, 290])

    result_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor(prediction_color)),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
    ]))

    elements.append(result_table)
    elements.append(Spacer(1, 25))

    # Description
    heading3 = Paragraph("<b>Job Description</b>", styles["Heading2"])
    elements.append(heading3)
    elements.append(Spacer(1, 10))

    desc = job_data.get("description", "No description provided")

    description = Paragraph(
        desc[:1500],
        styles["BodyText"]
    )

    elements.append(description)
    elements.append(Spacer(1, 25))

    # Footer
    footer = Paragraph(
        f"""
        <font size=10 color='grey'>
        Generated by JobGuard AI • {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}
        </font>
        """,
        styles["Normal"]
    )

    elements.append(footer)

    doc.build(elements)

    return str(filepath)